[package]
name = "vleue_kinetoscope"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13", default-features = false, features = [
    "bevy_sprite",
] }
image = { version = "0.24", default-features = false, features = ["gif"] }

[dev-dependencies]
bevy = { version = "0.13", default-features = false, features = [
    "bevy_sprite",
    "bevy_ui",
    "bevy_winit",
    "default_font",
] }
